spring:
  application:
    name: gachireel

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.pdclnjcicvtdjniksdpu
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  mail:
    # Gmail SMTP 서버 주소
    host: smtp.gmail.com
    # STARTTLS 방식의 표준 포트
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          # SMTP 인증 사용 (필수)
          auth: true
          starttls:
            # 보안 연결(TLS) 사용 (필수)
            enable: true
            required: true
          timeout: 5000

server:
  port: 8080

app:
  frontend-url: ${FRONTEND_URL}

springdoc:
  swagger-ui:
    path: /swagger.html
    url: /docs/openapi3.yaml

constants:
  jwt:
    issuer: gachireel
    bearer-format: JWT
    claim-key: user
    secret-key: ${JWT_SECRET}
    access-token-cookie-name: GAT
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 1800        # 30분
    access-token-validity-milliseconds: 1800000       # 30분
    refresh-token-cookie-name: GRT
    refresh-token-cookie-path: /api/auth
    refresh-token-cookie-validity-seconds: 1209600    # 14일
    refresh-token-validity-milliseconds: 1209600000   # 14일
